name: PlugMan
version: '${project.version}'
main: de.tamion.PlugMan
api-version: 1.19
authors: [Tamion]
description: Allows you to manage and download Plugin

commands:
  toggleplugin:
  deleteconfig:
  setconfig:
  reloadplugin: